### ISSUE TITLE
Request reply support fails

### ISSUE THREAD

**Issue by YoeriVD** [asyncapi/dotnet-nats-template#233]
#### Describe the bug
Request/Reply bindings are generated as normal async subscriptions and take a non existent request object as parameter

#### How to Reproduce
Add the following to any channel:
```yml
bindings:
      nats:
        is: requestReply
        requestReply:
          is: replier
        bindingVersion: 0.1.0
```

#### Expected behavior
Request reply behaviour is generated as methods that return the response.
